import type { Metadata } from "next";
import { Cairo, Outfit } from "next/font/google";
import "../globals.css";
import { cn } from "@/lib/utils";
import ToggleTheme from "@/components/theme-toggle";
import NavigationSheet, {
  NavigationMenuDesktop,
} from "./components/navigation";
import Image from "next/image";
import LocaleSwitcher from "@/components/locale-switcher";
import { MdOutlinePermPhoneMsg } from "react-icons/md";
import LangRenderer from "@/components/lang";
import Footer from "./components/footer";

const outfit = Outfit({ subsets: ["latin"] });
const cairo = Cairo({ subsets: ["arabic"] });

export const metadata: Metadata = {
  title: "المركز الليبي لبحوث اللدائن",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{
    lang: string;
  }>;
}>) {
  const lang = (await params).lang;
  return (
    <div
      lang={lang}
      dir={lang === "ar" ? "rtl" : "ltr"}
      className={cn(
        lang === "ar" ? cairo.className : outfit.className,
        "relative"
      )}
    >
      <header className="fixed z-[1000] w-full bg-background top-0 left-0 ">
        <div className="bg-primary selection:bg-secondary selection:text-foreground text-white px-4 flex justify-between items-center">
          <div className="flex gap-2 items-center">
            <LangRenderer
              ar={
                <>
                  <span>218928666458+</span>
                  <MdOutlinePermPhoneMsg size={24} />
                </>
              }
              en={
                <>
                  <MdOutlinePermPhoneMsg size={24} />
                  <span>+218928666458</span>
                </>
              }
            />
          </div>
          <LocaleSwitcher
            arTitle="عربي"
            className={cn(
              "text-white/80 font-normal hover:text-white pl-14",
              lang === "en" && "pl-0"
            )}
            enTitle="English"
            varians={"link"}
          />
        </div>
        <div dir="rtl" className="flex justify-between container items-center">
          <ToggleTheme className="phone-only:hidden" />
          <NavigationSheet />
          <NavigationMenuDesktop />
          <div className="md:w-24 w-16 overflow-hidden">
            <Image
              src={"/logo.png"}
              alt="logo"
              width={1000}
              height={1000}
              priority
              className="w-full h-full object-center object-cover"
            />
          </div>
        </div>
      </header>
      <div className="md:mt-32 mt-24">{children}</div>
      <Footer lang={lang} />
    </div>
  );
}
